apiVersion: apps/v1
kind: Deployment
metadata:
  name: arroz-frontend
  namespace: aplicacioncilla
spec:
  selector:
    matchLabels:
      aplicacion: arroz-frontend
  replicas: 1
  template:
    metadata:
      labels:
        aplicacion: arroz-frontend
    spec:
      containers:
        - name: api-frontend
          image: php:8.2-apache
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: project
      volumes:
        - name: project
          hostPath:
            path: /Users/gonzalo.martinez/Desktop/kubernetito/frontend
            type: Directory