apiVersion: v1
kind: Service
metadata:
  name: arroz-frontend
  namespace: aplicacioncilla
spec:
  type: NodePort
  selector:
    aplicacion: arroz-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30301
