apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: aplicacioncilla
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
