apiVersion: v1
kind: Service
metadata:
  name: arroz-api
  namespace: aplicacioncilla
spec:
  selector:
    aplicacion: arroz-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: aplicacioncilla
spec:
  selector:
    aplicacion: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
