apiVersion: v1
kind: Service
metadata:
  name: mail-api
  namespace: aplicacioncilla
spec:
  type: NodePort
  selector:
    aplicacion: mail-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30200
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: aplicacioncilla
spec:
  type: NodePort
  selector:
    aplicacion: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30201
---
apiVersion: v1
kind: Service
metadata:
  name: mail-server
  namespace: aplicacioncilla
spec:
  type: NodePort
  selector:
    aplicacion: mail-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
      nodePort: 30202
    - protocol: TCP
      port: 25
      targetPort: 25
      nodePort: 30203
      name: smtp