apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-api
  namespace: aplicacioncilla
spec:
  selector:
    matchLabels:
      aplicacion: mail-api
  replicas: 1
  template:
    metadata:
      labels:
        aplicacion: mail-api
    spec:
      containers:
        - name: api-mail
          image: ggmartinez/queues:v2
          ports:
            - containerPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-listener
  namespace: aplicacioncilla
spec:
  selector:
    matchLabels:
      aplicacion: queue-listener
  replicas: 1
  template:
    metadata:
      labels:
        aplicacion: mail-api
    spec:
      containers:
        - name: mail-api
          image: ggmartinez/queues:v2
          args:
            - php
            - artisan
            - queue:work

