apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-server
  namespace: aplicacioncilla
spec:
  selector:
    matchLabels:
      aplicacion: mail-server
  replicas: 1
  template:
    metadata:
      labels:
        aplicacion: mail-server
    spec:
      containers:
        - name: mail-server
          image: rnwood/smtp4dev
          ports:
            - containerPort: 80
              name: web
            - containerPort: 25
              name: smtp
