apiVersion: v1
kind: Service
metadata:
  name: mail-api
  namespace: aplicacioncilla
spec:
  selector:
    aplicacion: mail-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: mail-server
  namespace: aplicacioncilla
spec:
  selector:
    aplicacion: mail-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
    - protocol: TCP
      port: 25
      targetPort: 25
      name: smtp
