apiVersion: apps/v1
kind: Deployment
metadata:
  name: arroz-api
  namespace: aplicacioncilla
spec:
  selector:
    matchLabels:
      aplicacion: arroz-api
  replicas: 1
  template:
    metadata:
      labels:
        aplicacion: arroz-api
    spec:
      containers:
        - name: api-arroz
          image: ggmartinez/laravel:php-82-Xdebug
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /app
              name: project
      volumes:
        - name: project
          hostPath:
            path: /Users/gonzalo.martinez/Desktop/kubernetito/backend
            type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: aplicacioncilla
spec:
  selector:
    matchLabels:
      aplicacion: mysql
  replicas: 1
  template:
    metadata:
      labels:
        aplicacion: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
              name: web 
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: aplicacioncilla

          