apiVersion: v1
kind: Service
metadata:
  name: arroz-api
  namespace: aplicacioncilla
spec:
  type: NodePort
  selector:
    aplicacion: arroz-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30300
---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: aplicacioncilla
spec:
  type: NodePort
  selector:
    aplicacion: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30201